{
    'name': 'NHCL Custom App',
    'summary': 'NHCL Customization works',
    'author': 'New Horizons Cybersoft Ltd',
    'company': 'New Horizons Cybersoft Ltd',
    'maintainer': 'New Horizons Cybersoft Ltd',
    'website': "https://www.nhclindia.com/",
    'version': '1.0',
    'sequence': 1,
    'depends': ['base', 'purchase', 'account', 'analytic', 'project', 'approvals', 'account_budget', 'mail',
                'project_account_budget', 'stock', 'uom', 'product', 'approvals_purchase', 'sale', 'sale_project','sale_management',],
    'data': [
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'views/nhcl_account_move_views.xml',
        'views/project.xml',
        'views/revise_budget.xml',
        'views/purchase.xml',
        'views/nhcl_stock_views.xml',
        'views/approval_request_views.xml',
        'views/approval_product_line_views.xml',
        'data/cron_jobs.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
    "license": "LGPL-3",
}
